sudo: false  # to use container-based infra, see: http://docs.travis-ci.com/user/migrating-from-legacy/
notifications:
  email:
    - deepdive-dev@lists.stanford.edu
  webhooks:
    urls:
      # gitter.im/HazyResearch/deepdive
      - https://webhooks.gitter.im/e/ee3a2470727e53cdc3c3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
language:
  - c
  - cpp
  - python
  - scala
jdk:
  - openjdk7
python:
  - "2.7"
services:
  - postgresql

cache:
  directories:
    - .build/submodule
    - extern/.build
    - $HOME/.ivy2/cache

env:
  global:
    - PGUSER: postgres
    - PGPASSWORD:
    - PGPORT: 5432
    - PGHOST: localhost
    - DBNAME: deepdive_test
# Parallel jobs aren't effective since the `install` step currently takes most of the time.
#  matrix: # NOTE we're on a paid plan that gives us 2 parallel jobs
#      # 1. Unit tests with PostgreSQL and integration tests with MySQL
#    - TEST_ONLY: "'test/postgresql/scalatests.bats test/mysql/*.bats'"
#      TEST_EXCEPT: test/mysql/scalatests.bats
#      # 2. More integration tests with PostgreSQL
#    - TEST_ONLY:
#      TEST_EXCEPT: "'test/postgresql/scalatests.bats test/mysql/*.bats'"

before_install:
  # Check coding style before performing the build and tests
  - make checkstyle

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test  # for gcc 4.8
    packages:
    - gnuplot
    - bc
    - bzip2
      # for building sampler
    - libnuma-dev
    - gcc-4.8
    - g++-4.8
      # for mindbender
    - ed

install:
#  - make depends # XXX does not work on container-based infra
  - export CXX="g++-4.8" CC="gcc-4.8" # necessary for building sampler
  - make test-build

script:
  # Run all tests
  - make test

  # Check broken links in documentation
  # TODO check only when doc/ has changed
  #- make -C doc/ linkcheck
