language: scala
scala:
    - "2.11.1"

sudo: false  # to use container-based infrastructure
addons:
    apt:
        packages:
            - wdiff
cache:
    directories:
        - $HOME/.ivy2/cache

script:
    - make test MEASURE_COVERAGE=true
after_success:
    - sbt coverageReport coveralls
