sudo: false  # to use container-based infra, see: http://docs.travis-ci.com/user/migrating-from-legacy/
addons:
  apt:
    sources:
    # for gcc 4.8
    - ubuntu-toolchain-r-test
    packages:
    # for building sampler
    - libnuma-dev
    - gcc-4.8
    - g++-4.8

language: cpp
notifications:
  email:
    - deepdive-dev@lists.stanford.edu
before_install:
  - export CXX="g++-4.8" CC="gcc-4.8"
install: make dep
compiler:
  - gcc
# Change this to your needs
script: make test
