# Travis CI config to run tests using Docker
# See: https://docs.travis-ci.com/user/docker/
# See: https://docker.io/
sudo: required
dist: trusty
language: c  # C seems to have the least amount of setup
services:
  - docker

notifications:
  email:
    - deepdive-notifications@cs.stanford.edu
    # XXX Routing notifications through cs.stanford.edu as Travis cannot directly send to googlegroups.com
    # See: https://github.com/travis-ci/travis-ci/issues/2513
    #- deepdive-dev@googlegroups.com
  webhooks:
    urls:
      # gitter.im/HazyResearch/deepdive
      - https://webhooks.gitter.im/e/ee3a2470727e53cdc3c3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  # Check coding style before performing the build and tests
  - make checkstyle

  # Have Docker build scripts use and update the correct images
  - export DOCKER_IMAGE=netj/deepdive-build
  - export DOCKER_IMAGE_MASTER=$DOCKER_IMAGE:master
  - export DOCKER_IMAGE_TEST_PREFIX=$DOCKER_IMAGE:travis-$TRAVIS_JOB_NUMBER-${TRAVIS_COMMIT:0:7}-

install:
  # Build using Docker
  - util/build/docker/build-in-container

script:
  # Run all tests
  - util/build/docker/test-in-container-postgres

  # Check broken links in documentation
  # TODO check only when doc/ has changed
  #- make -C doc/ linkcheck

#after_success:
#  - docker login ...
#  - docker push $DOCKER_IMAGE
#  - docker push ${DOCKER_IMAGE_TEST_PREFIX}PASS
#after_failure:
#  - docker login ...
#  - docker push $DOCKER_IMAGE
#  - docker push ${DOCKER_IMAGE_TEST_PREFIX}FAIL

#before_deploy:
#  - TODO docker cp ...

## update GitHub releases for some select branches (master and v*.*.x)
#deploy:
#  - provider: script
#    script: util/build/decrypt-travis-then-update-github-releases
#    skip_cleanup: true
#    on:
#      repo: HazyResearch/deepdive
#      all_branches: true
#      # TODO condition: "$TRAVIS_BRANCH = master || $TRAVIS_BRANCH = v*.*.x"
#  - provider: script
#    script: util/build/decrypt-travis-then-update-github-releases
#    skip_cleanup: true
#    on:
#      repo: HazyResearch/deepdive
#      tag: true
