package:
  name: deepdive
  version: {{ GIT_DESCRIBE_TAG|replace("v","") }}

source:
  git_url: ../

build:
  script_env:
    - USER
  number: {{ GIT_DESCRIBE_NUMBER|int }}

test:
  files:
    - examples/smoke
  commands:
    - cd examples/smoke
    - echo 'postgresql://postgres@localhost/deepdive_smoke_\$USER' > db.url
    - deepdive run

requirements:
  build:
    - python
    - setuptools
    - coreutils >=8.21
    - cmake
    - unzip
    - gnu-wget

  run:
    - python
    - pyhocon
    - coreutils >=8.21
    - moreutils >=0.59
    - jq ==1.5
    - graphviz >=2.38.0
    - bc
    - pv >=1.6.0
    - pbzip2
    - bash ==4.3.42
    - gnuplot

# # for building deepdive, not available as a conda package
# # on a bare Ubuntu Xenial AMI:
# sudo apt-get update
# sudo apt-get install make
# sudo apt-get install unzip
# sudo apt-get install gcc
